/* Basic ESPNOW Example - Slave
   This is a very basic example of sending data to the complementary Master example.
   By default, it sends an unencrypted data packet containing a random value and the state of a button to the broadcast mac address.
   To customise for your data:
    - Alter my_data_t in espnow_basic_config
    - Alter my_data_receive my_master.c
    - Alter my_data_populate my_slave.c
   For basic demonstration, do not edit this file
*/

#include <stdlib.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "nvs_flash.h"
#include "esp_event.h"
#include "esp_netif.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_now.h"
#include "esp_sleep.h"
#include <driver/adc.h>
#include "freertos/queue.h"
#include <stdio.h>
#include "driver/gpio.h"

#include "sdkconfig.h"

#include "espnow_basic_config.h"

static const char *TAG = "Basic_Slave";

static char tag[] = "adc1";

void my_data_populate(my_data_t *data);

static xQueueHandle s_send_queue;

typedef enum {
    EXAMPLE_ESPNOW_SEND_CB,
    EXAMPLE_ESPNOW_RECV_CB,
} example_espnow_event_t;

#define MY_ESPNOW_WIFI_MODE WIFI_MODE_STA
#define MY_ESPNOW_WIFI_IF   ESP_IF_WIFI_STA
// #define MY_ESPNOW_WIFI_MODE WIFI_MODE_AP
// #define MY_ESPNOW_WIFI_IF   ESP_IF_WIFI_AP


static void send_data_task(void *pvParameter)
{
    example_espnow_event_t evt;
    const uint8_t destination_mac[] = MY_RECEIVER_MAC;

    my_data_t *data = (my_data_t *)pvParameter;

    ESP_LOGI(TAG, "Sending %u bytes to " MACSTR, sizeof(my_data_t), MAC2STR(destination_mac));
    esp_err_t err = esp_now_send(destination_mac, (uint8_t*)data, sizeof(my_data_t));

    if(err != ESP_OK) {
        ESP_LOGE(TAG, "Send error (%d)", err);
    }

    while (xQueueReceive(s_send_queue, &evt, portMAX_DELAY) == pdTRUE) {

        my_data_populate(data);

        ESP_LOGI(TAG, "Sending %u bytes to " MACSTR, sizeof(my_data_t), MAC2STR(destination_mac));
        esp_err_t err = esp_now_send(destination_mac, (uint8_t*)data, sizeof(my_data_t));


    	printf("Data: Button - %s, Switch - %s, xcar - %u, ycar - %u, xcam - %u\n",
    	data->button_pushed ? "Pushed" : "Released",
    	data->switch_flicked ? "Pushed" : "Released",
    	data->xcar, data->ycar,
    	data->xcam);


        if(err != ESP_OK) {
            ESP_LOGE(TAG, "Send error (%d)", err);
        }
    }

}

static void packet_sent_cb(const uint8_t *mac_addr, esp_now_send_status_t status)
{
    example_espnow_event_t evt;

    if (mac_addr == NULL) {
        ESP_LOGE(TAG, "Send cb arg error");
        return;
    }

    evt = EXAMPLE_ESPNOW_SEND_CB;

    if (xQueueSend(s_send_queue, &evt, portMAX_DELAY) != pdTRUE) {
        ESP_LOGW(TAG, "Send send queue fail");
    }

}

static void init_espnow_slave(void)
{
    my_data_t *data;

    const wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK( nvs_flash_erase() );
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK( ret );

    ESP_ERROR_CHECK( esp_netif_init() );
    ESP_ERROR_CHECK( esp_event_loop_create_default() );
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
    ESP_ERROR_CHECK( esp_wifi_set_storage(WIFI_STORAGE_RAM) );
    ESP_ERROR_CHECK( esp_wifi_set_mode(MY_ESPNOW_WIFI_MODE) );
    ESP_ERROR_CHECK( esp_wifi_start() );
#if MY_ESPNOW_ENABLE_LONG_RANGE
    ESP_ERROR_CHECK( esp_wifi_set_protocol(MY_ESPNOW_WIFI_IF, WIFI_PROTOCOL_11B|WIFI_PROTOCOL_11G|WIFI_PROTOCOL_11N|WIFI_PROTOCOL_LR) );
#endif

    s_send_queue = xQueueCreate(10, sizeof(example_espnow_event_t));
    assert(s_send_queue);

    ESP_ERROR_CHECK( esp_now_init() );
    ESP_ERROR_CHECK( esp_now_register_send_cb(packet_sent_cb) );
    ESP_ERROR_CHECK( esp_now_set_pmk((const uint8_t *)MY_ESPNOW_PMK) );

    // Alter this if you want to specify the gateway mac, enable encyption, etc
    const esp_now_peer_info_t broadcast_destination = {
        .peer_addr = MY_RECEIVER_MAC,
        .channel = MY_ESPNOW_CHANNEL,
        .ifidx = MY_ESPNOW_WIFI_IF
    };
    ESP_ERROR_CHECK( esp_now_add_peer(&broadcast_destination) );

    data = malloc(sizeof(my_data_t));
    my_data_populate(data);

    xTaskCreate(send_data_task, "send_data_task", 8192, data, 4, NULL);

}


void app_main(void)
{
	//from joystick
	ESP_LOGD(tag, "adc1");
	adc1_config_width(ADC_WIDTH_12Bit);
	adc1_config_channel_atten(ADC1_CHANNEL_7, ADC_ATTEN_11db);
	adc1_config_channel_atten(ADC1_CHANNEL_6, ADC_ATTEN_11db);
	adc1_config_channel_atten(ADC1_CHANNEL_4, ADC_ATTEN_11db);

    init_espnow_slave();

    //esp_deep_sleep(1000ULL * MY_SLAVE_DEEP_SLEEP_TIME_MS);
}
